import ConceptBlock from '../../../components/content/ConceptBlock.jsx'
import SDKExample from '../../../components/content/SDKExample.jsx'
import NoteBlock from '../../../components/content/NoteBlock.jsx'
import BestPracticeBlock from '../../../components/content/BestPracticeBlock.jsx'
import WarningBlock from '../../../components/content/WarningBlock.jsx'

export default function UnitIntegrationTestGeneration() {
  return (
    <article className="prose-content">
      <h1>Unit and Integration Test Generation</h1>

      <p>
        Test generation is one of the highest-leverage applications of AI in the development
        workflow. Writing tests is cognitively demanding but structurally predictable: you need
        to understand the function's contract, enumerate the cases that matter, write the assertions
        that verify each case. Claude excels at the mechanical parts of this work while you retain
        the judgment about which cases actually matter for your domain.
      </p>

      <p>
        The key discipline is directing Claude toward tests that verify behavior rather than
        tests that achieve coverage metrics. A test suite where every function has 100% line
        coverage but no assertion would fail every CI run if the coverage tool treated a
        <code>console.log</code> as a statement — and yet that suite would be useless. Coverage
        is a floor, not a ceiling. The ceiling is: does this test catch real regressions?
      </p>

      <ConceptBlock title="Test Generation Strategy: Outside-In">
        The most effective AI test generation strategy is outside-in: start with the
        public contract (what callers expect), then work inward to edge cases and internal
        invariants. Ask Claude to enumerate the cases for a function before writing any
        tests — "what are all the ways this function could be called, and what should happen
        in each case?" Use that enumeration as the test plan, then have Claude implement
        tests for each case.
      </ConceptBlock>

      <SDKExample
        title="Generating Unit Tests From Implementation"
        tabs={[
          {
            label: 'bash',
            language: 'bash',
            filename: 'generate-unit-tests.sh',
            code: `# Generate unit tests for an existing function
claude "Generate comprehensive unit tests for the calculateShippingCost function
in src/domain/shipping/calculator.ts.

Before writing any tests, enumerate all test cases:
1. Valid inputs: what are the normal cases?
2. Boundary conditions: minimum/maximum values, exact thresholds
3. Invalid inputs: null, undefined, negative values, wrong types
4. Business rules: what invariants must always hold?
5. Error conditions: when should it throw vs return an error value?

Then implement tests for each case using Jest.
Each test must:
- Have a descriptive name that reads as a behavior statement (not 'test case 1')
- Have exactly one assertion per test (or group related assertions with a comment)
- Use factories/builders for test data (not inline object literals)
- NOT mock the function under test (only mock its external dependencies)

Run: npm test -- --testPathPattern='calculator' after writing
Target: all tests pass, function coverage > 90%"`,
          },
          {
            label: 'typescript',
            language: 'typescript',
            filename: 'tests/shipping/calculator.test.ts (generated)',
            code: `// Generated by Claude Code — reviewed and approved by engineer
import { calculateShippingCost } from '../../src/domain/shipping/calculator'
import { ShipmentBuilder } from '../factories/ShipmentBuilder'
import { AddressBuilder } from '../factories/AddressBuilder'

describe('calculateShippingCost', () => {
  describe('standard domestic shipments', () => {
    it('calculates base rate for shipment under 1kg', () => {
      const shipment = new ShipmentBuilder().withWeight(0.5).build()
      expect(calculateShippingCost(shipment)).toEqual({ amount: 4.99, currency: 'USD' })
    })

    it('applies weight surcharge for shipments 1kg to 10kg', () => {
      const shipment = new ShipmentBuilder().withWeight(5).build()
      const cost = calculateShippingCost(shipment)
      expect(cost.amount).toBeGreaterThan(4.99)
      expect(cost.amount).toBeLessThan(20)
    })

    it('applies heavy freight rate for shipments over 10kg', () => {
      const shipment = new ShipmentBuilder().withWeight(15).build()
      const cost = calculateShippingCost(shipment)
      expect(cost.amount).toBeGreaterThanOrEqual(25)
    })
  })

  describe('boundary conditions', () => {
    it('treats exactly 1kg as standard (not surcharge) rate', () => {
      const at1kg = new ShipmentBuilder().withWeight(1).build()
      const below1kg = new ShipmentBuilder().withWeight(0.999).build()
      expect(calculateShippingCost(at1kg).amount).toBe(calculateShippingCost(below1kg).amount)
    })
  })

  describe('invalid inputs', () => {
    it('throws for zero weight', () => {
      const shipment = new ShipmentBuilder().withWeight(0).build()
      expect(() => calculateShippingCost(shipment)).toThrow('Weight must be positive')
    })

    it('throws for negative weight', () => {
      const shipment = new ShipmentBuilder().withWeight(-1).build()
      expect(() => calculateShippingCost(shipment)).toThrow('Weight must be positive')
    })
  })
})`,
          },
        ]}
      />

      <h2>Mutation Testing: Verifying Test Quality</h2>

      <p>
        Mutation testing answers the question that coverage metrics cannot: if this line of code
        were wrong, would a test catch it? A mutation testing tool modifies your code in small
        ways (flipping a <code>&gt;</code> to <code>&gt;=</code>, changing a <code>+</code> to
        a <code>-</code>), runs the test suite, and reports whether any tests failed. If no
        test fails for a mutation, that mutation "survived" — meaning you have dead tests or
        missing cases.
      </p>

      <SDKExample
        title="Mutation Testing with Stryker"
        tabs={[
          {
            label: 'bash',
            language: 'bash',
            filename: 'mutation-testing.sh',
            code: `# Install Stryker mutation testing framework
npm install --save-dev @stryker-mutator/core @stryker-mutator/jest-runner

# Run mutation tests on a specific module
npx stryker run --mutate 'src/domain/shipping/calculator.ts'

# Ask Claude to fix surviving mutants
claude "Stryker mutation testing found surviving mutants in src/domain/shipping/calculator.ts.

Surviving mutants report:
$(npx stryker run --mutate 'src/domain/shipping/calculator.ts' --reporters json 2>/dev/null | jq '.mutants[] | select(.status == \"Survived\") | {id, mutatorName, location, replacement}')

For each surviving mutant:
1. Understand what code change the mutant made
2. Determine which business behavior that change would break
3. Write a test that would catch that regression
4. Add the test to the existing test file
5. Re-run Stryker to verify the mutant is now killed

Target: mutation score > 80%"`,
          },
        ]}
      />

      <h2>Integration Test Generation</h2>

      <p>
        Integration tests verify that components work together correctly — a service with its
        database, an API with its authentication middleware, a message handler with its queue.
        Claude can generate integration tests from API contracts and data models, but needs
        explicit context about the infrastructure being integrated.
      </p>

      <SDKExample
        title="Generating Integration Tests for a REST API"
        tabs={[
          {
            label: 'bash',
            language: 'bash',
            filename: 'generate-integration-tests.sh',
            code: `# Generate integration tests for the Orders API
claude "Generate integration tests for the Orders API.

Context:
- API spec: docs/api/orders-api.yaml (OpenAPI 3.0)
- Database: PostgreSQL via TypeORM, test database: process.env.TEST_DATABASE_URL
- Auth: JWT bearer token — use TEST_JWT_SECRET env var to generate test tokens
- Test framework: Jest + Supertest

For each endpoint in the OpenAPI spec, generate:
1. Happy path test with valid data
2. Authentication failure test (missing/invalid token)
3. Validation error test (invalid request body)
4. Not-found test (for endpoints with resource IDs)
5. At least one test for documented error responses

Test setup requirements:
- Use beforeEach to reset database state (truncate tables, not drop)
- Use a factory function to create test users and generate their JWT tokens
- All tests must be independent — no test should depend on another's side effects

Run: npm run test:integration after generating
All tests must pass against a real test database (not mocked)."`,
          },
        ]}
      />

      <WarningBlock title="Review Generated Tests for Vacuous Assertions">
        Claude sometimes generates tests that technically pass but assert nothing meaningful.
        Watch for: <code>expect(result).toBeDefined()</code> (always true unless result is
        undefined), <code>expect(result).toBeTruthy()</code> (passes for any non-empty value),
        or tests that call the function but never assert on the return value. Before accepting
        any generated test file, read each assertion and ask: "Would this test fail if I removed
        the relevant business logic?"
      </WarningBlock>

      <BestPracticeBlock title="Use Test Factories, Not Inline Data">
        When Claude generates tests, instruct it to use test factory functions rather than
        inline object literals. Factories make tests more maintainable — when a model changes,
        you update the factory once rather than 40 test files. Ask Claude: "Create a UserFactory
        and OrderFactory in tests/factories/ before generating the tests. All test data should
        come from these factories." This also surfaces a useful side effect: Claude will often
        discover inconsistencies in your data model when it tries to build a factory for it.
      </BestPracticeBlock>

      <NoteBlock type="tip" title="Characterization Tests for Legacy Code">
        For code with no existing tests, use characterization tests: tests that document
        what the code currently does, rather than what it should do. Ask Claude: "Write
        characterization tests for src/legacy/OrderProcessor.ts. The tests should capture
        the current behavior by calling the code with various inputs and recording what
        it returns. Do not change the implementation. These tests will protect us during
        future refactoring." Characterization tests are the prerequisite for safe refactoring
        of untested legacy code.
      </NoteBlock>
    </article>
  )
}
