import ConceptBlock from '../../../components/content/ConceptBlock.jsx'
import SDKExample from '../../../components/content/SDKExample.jsx'
import NoteBlock from '../../../components/content/NoteBlock.jsx'
import BestPracticeBlock from '../../../components/content/BestPracticeBlock.jsx'

export default function ArchitectureDocFreshness() {
  return (
    <article className="prose-content">
      <h1>Architecture Document Freshness</h1>

      <p>
        Architecture diagrams are the most-referenced and least-maintained form of engineering
        documentation. A C4 diagram drawn when the system was designed accurately describes
        the intended architecture. A year later, after dozens of microservices were added,
        three were decomposed, and two external integrations were swapped for alternatives,
        that diagram describes a system that no longer exists. Developers continue citing it
        because nothing replaced it, and so incorrect mental models propagate.
      </p>

      <p>
        The solution is diagrams-as-code: architecture diagrams generated from the actual
        codebase and dependency graph, updated automatically when the codebase changes.
        Claude can generate and maintain Mermaid diagrams and C4 models directly from code
        analysis, ensuring the documentation reflects what was actually built.
      </p>

      <ConceptBlock title="Diagrams-as-Code">
        Mermaid is a markdown-like syntax for diagrams that renders in GitHub, GitLab, Notion,
        and most modern documentation platforms. C4 is a hierarchical model for software
        architecture covering Context, Containers, Components, and Code. When architecture
        diagrams are stored as text in the repository, they can be version-controlled, reviewed
        in PRs, and generated by Claude from code analysis rather than manually drawn.
      </ConceptBlock>

      <SDKExample
        title="Generating Architecture Diagrams from Code"
        tabs={[
          {
            label: 'bash',
            language: 'bash',
            filename: 'generate-architecture-docs.sh',
            code: `# Generate a Mermaid system context diagram from the codebase
claude "Analyze our codebase and generate architecture documentation.

Step 1: Analyze the system
- Read src/config/external-services.ts for external service integrations
- Read src/infrastructure/ for infrastructure adapters (database, cache, queue)
- Read package.json for major dependencies
- Read docker-compose.yml for local service topology

Step 2: Generate a C4 System Context Diagram (Mermaid)
Format:
mermaid
C4Context
  title System Context Diagram — MyApp

  Person(user, 'Customer', 'Uses the web application')
  Person(admin, 'Admin', 'Manages platform settings')

  System(myapp, 'MyApp', 'E-commerce platform')

  System_Ext(stripe, 'Stripe', 'Payment processing')
  System_Ext(sendgrid, 'SendGrid', 'Transactional email')
  System_Ext(auth0, 'Auth0', 'Identity and authentication')

  Rel(user, myapp, 'Shops, places orders')
  Rel(admin, myapp, 'Manages products, orders')
  Rel(myapp, stripe, 'Processes payments', 'HTTPS/REST')
  Rel(myapp, sendgrid, 'Sends emails', 'HTTPS/REST')
  Rel(myapp, auth0, 'Authenticates users', 'OAuth 2.0/OIDC')


Step 3: Generate a Container Diagram showing internal services
Step 4: Write to docs/architecture/README.md
Step 5: Note the generation date and commit hash in the diagram header"`,
          },
          {
            label: 'yaml',
            language: 'yaml',
            filename: 'CLAUDE.md (architecture docs)',
            code: `## Architecture Documentation Maintenance

### Diagrams
Location: docs/architecture/
Diagrams must be regenerated when:
- A new external service integration is added
- A new microservice or major module is created
- A service is deprecated or removed
- A significant architectural decision is implemented (see ADRs)

### Regeneration Command
Run: claude "Regenerate architecture diagrams in docs/architecture/ based on the
current codebase. Compare to the existing diagrams and list what changed."

### C4 Diagram Levels
- Level 1 (Context): docs/architecture/c4-context.md — external actors and systems
- Level 2 (Container): docs/architecture/c4-containers.md — deployable units
- Level 3 (Component): docs/architecture/c4-components-{service}.md — per service

### Validation
Architecture diagrams are reviewed by tech leads in architecture review meetings (bi-weekly)
Out-of-date diagrams flagged with: <!-- STALE: regenerate after {event} -->`,
          },
        ]}
      />

      <h2>Automated Diagram Updates on Code Changes</h2>

      <SDKExample
        title="CI-Triggered Architecture Doc Updates"
        tabs={[
          {
            label: 'yaml',
            language: 'yaml',
            filename: '.github/workflows/update-architecture-docs.yml',
            code: `name: Update Architecture Documentation

on:
  push:
    branches: [main]
    paths:
      - 'src/infrastructure/**'
      - 'src/config/external-services.ts'
      - 'docker-compose.yml'
      - 'package.json'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${'$'}{{ secrets.GITHUB_TOKEN }}

      - name: Generate dependency graph
        run: |
          npm ci
          npx depcruise src/ --output-type dot > /tmp/dependency-graph.dot
          dot -Tsvg /tmp/dependency-graph.dot > docs/architecture/dependency-graph.svg

      - name: Validate Mermaid diagrams
        run: |
          # Check that all .mermaid files in docs/ are valid syntax
          find docs/ -name "*.mermaid" -exec npx @mermaid-js/mermaid-cli -i {} -o /tmp/mermaid-check.svg \;

      - name: Commit updated diagrams
        run: |
          git config user.name "Architecture Bot"
          git config user.email "bot@example.com"
          git add docs/architecture/dependency-graph.svg
          git diff --staged --quiet || git commit -m "docs(arch): auto-update dependency graph [skip ci]"
          git push`,
          },
        ]}
      />

      <h2>C4 Model Maintenance Workflow</h2>

      <SDKExample
        title="Keeping C4 Models Current"
        tabs={[
          {
            label: 'bash',
            language: 'bash',
            filename: 'refresh-c4-models.sh',
            code: `# Monthly architecture doc refresh — run after significant changes
claude "Perform an architecture documentation audit.

Step 1: Read the current C4 diagrams in docs/architecture/

Step 2: Compare to reality by analyzing:
- All HTTP clients in src/ (external service integrations): 
  grep -r 'axios\|fetch\|http\.get' src/ --include='*.ts' -l
- All database models: ls src/domain/models/
- All message queue subscriptions: grep -r 'queue\|subscribe\|consumer' src/ -l
- All environment variables: cat .env.example

Step 3: For each discrepancy found (in code but not in diagram, or in diagram but not in code):
- List the discrepancy
- Generate the corrected diagram section

Step 4: Update the diagrams with corrections and add:
<!-- Last verified: $(date -I) by architecture audit -->
<!-- Commit: $(git rev-parse --short HEAD) -->

Step 5: List any new services or integrations that should be added to the
docs/architecture/decisions/ ADR log."`,
          },
        ]}
      />

      <BestPracticeBlock title="Stale Diagram Markers">
        When you know a diagram is about to become stale — a new integration is being
        planned, a service is being deprecated — add a marker comment to the diagram
        before the work begins: <code>&lt;!-- PLANNED CHANGE: add {service} integration
        after {ticket} merges --&gt;</code>. This alerts readers that the diagram will
        be updated, and it gives Claude a clear signal when the work completes:
        "Remove all PLANNED CHANGE markers from architecture docs and regenerate the
        affected diagrams to reflect the completed change." This pattern prevents the
        diagram from being treated as current when it is deliberately temporary.
      </BestPracticeBlock>

      <NoteBlock type="tip" title="Structurizr for Complex Enterprise Architecture">
        For organizations with dozens of services and complex architecture, Structurizr
        provides a code-first architecture description language (Structurizr DSL) that
        generates multiple diagram levels from a single model definition. Claude can
        generate and maintain Structurizr DSL files from code analysis. The DSL is
        stored in the repository, rendered on commit, and can be exported to multiple
        formats including Mermaid, PlantUML, and the Structurizr web viewer. This scales
        better than maintaining individual Mermaid diagrams for large systems.
      </NoteBlock>
    </article>
  )
}
