import ConceptBlock from '../../../components/content/ConceptBlock.jsx'
import SDKExample from '../../../components/content/SDKExample.jsx'
import NoteBlock from '../../../components/content/NoteBlock.jsx'
import BestPracticeBlock from '../../../components/content/BestPracticeBlock.jsx'
import WarningBlock from '../../../components/content/WarningBlock.jsx'

export default function InfrastructureAsCode() {
  return (
    <article className="prose-content">
      <h1>Infrastructure as Code</h1>

      <p>
        Infrastructure as Code (IaC) applies software engineering discipline to the definition
        and management of infrastructure: servers, databases, networks, and cloud services
        are defined in code, version-controlled, reviewed in PRs, and deployed through
        automated pipelines. Claude accelerates IaC authoring significantly — a Terraform
        module that would take an engineer a day to write, test, and document can be generated
        in an hour, with security scanning and best practices applied automatically.
      </p>

      <p>
        The discipline Vibe Engineering brings to IaC is the same it brings to application
        code: IaC changes go through PR review, security scanning runs before apply,
        and CLAUDE.md includes IaC conventions and security requirements that constrain
        what Claude generates.
      </p>

      <ConceptBlock title="IaC Security is Higher Stakes Than Application Security">
        A security vulnerability in application code affects the application layer.
        A security vulnerability in infrastructure code — an S3 bucket that is publicly
        readable, a security group that opens port 22 to 0.0.0.0/0, an IAM policy with
        wildcard permissions — can expose the entire cloud environment. IaC changes must
        be reviewed more carefully than application changes and must pass automated
        security scanning (Checkov, tfsec) before applying.
      </ConceptBlock>

      <SDKExample
        title="Generating Terraform with Security Scanning"
        tabs={[
          {
            label: 'bash',
            language: 'bash',
            filename: 'generate-terraform.sh',
            code: `# Generate Terraform for a new application component
claude "Generate Terraform for a new API service deployment on AWS ECS Fargate.

Requirements:
- Service: payment-api (Node.js, port 3000)
- Container image: ECR repository (to be created)
- CPU: 256, Memory: 512 (can scale to 2048/4096 under load)
- Auto-scaling: min 2 tasks, max 20 tasks, scale on CPU > 70%
- Networking: private subnet, behind ALB (existing ALB target group attachment)
- Secrets: payment-api secrets from AWS Secrets Manager (STRIPE_SECRET_KEY, DB_PASSWORD)
- Logging: CloudWatch Logs, 30-day retention
- IAM: minimum permissions (only the specific Secrets Manager ARNs it needs)

Security requirements (from CLAUDE.md):
- No public IP on ECS tasks
- IAM role must follow least-privilege (no wildcard actions or resources)
- CloudWatch log group must have encryption enabled
- ECR repository must have image scanning enabled
- All tags must include: Environment, Service, ManagedBy=terraform, Team

After generating:
1. Run: checkov -d infra/terraform/modules/payment-api/ --output cli
2. Fix any HIGH or CRITICAL findings
3. Run: tfsec infra/terraform/modules/payment-api/
4. Fix any HIGH findings

Place in: infra/terraform/modules/payment-api/"`,
          },
          {
            label: 'hcl',
            language: 'hcl',
            filename: 'infra/terraform/modules/payment-api/main.tf (generated)',
            code: `# ECS Fargate Service for payment-api
# Generated by Claude Code — reviewed by DevOps team
# Checkov: PASSED | tfsec: PASSED

locals {
  service_name = "payment-api"
  tags = {
    Environment = var.environment
    Service     = local.service_name
    ManagedBy   = "terraform"
    Team        = "payments"
  }
}

resource "aws_ecs_task_definition" "payment_api" {
  family                   = "\$\{var.environment\}-\$\{local.service_name\}"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = 256
  memory                   = 512
  execution_role_arn       = aws_iam_role.ecs_execution.arn
  task_role_arn            = aws_iam_role.ecs_task.arn

  container_definitions = jsonencode([{
    name  = local.service_name
    image = "\$\{aws_ecr_repository.payment_api.repository_url\}:\$\{var.image_tag\}"
    portMappings = [{
      containerPort = 3000
      protocol      = "tcp"
    }]
    secrets = [
      {
        name      = "STRIPE_SECRET_KEY"
        valueFrom = data.aws_secretsmanager_secret.stripe.arn
      },
      {
        name      = "DB_PASSWORD"
        valueFrom = data.aws_secretsmanager_secret.db_password.arn
      }
    ]
    logConfiguration = {
      logDriver = "awslogs"
      options = {
        "awslogs-group"         = aws_cloudwatch_log_group.payment_api.name
        "awslogs-region"        = data.aws_region.current.name
        "awslogs-stream-prefix" = local.service_name
      }
    }
    readonlyRootFilesystem = true  # CKV_DOCKER_3
    user                   = "1000"  # Non-root user
  }])

  tags = local.tags
}

resource "aws_cloudwatch_log_group" "payment_api" {
  name              = "/ecs/\$\{var.environment\}/\$\{local.service_name\}"
  retention_in_days = 30
  kms_key_id        = aws_kms_key.logs.arn  # CKV_AWS_158
  tags              = local.tags
}

resource "aws_ecr_repository" "payment_api" {
  name                 = "\$\{var.environment\}/\$\{local.service_name\}"
  image_tag_mutability = "IMMUTABLE"  # CKV_AWS_51

  image_scanning_configuration {
    scan_on_push = true  # CKV_AWS_163
  }

  encryption_configuration {
    encryption_type = "KMS"
    kms_key         = aws_kms_key.ecr.arn
  }

  tags = local.tags
}`,
          },
        ]}
      />

      <SDKExample
        title="Checkov IaC Security Scanning"
        tabs={[
          {
            label: 'bash',
            language: 'bash',
            filename: 'checkov-scan.sh',
            code: `# Scan Terraform with Checkov before applying
pip install checkov

# Scan a specific module
checkov -d infra/terraform/modules/ \
  --framework terraform \
  --output cli \
  --output sarif \
  --output-file-path /tmp/checkov-results

# Fail CI on HIGH/CRITICAL findings
checkov -d infra/terraform/ \
  --check HIGH,CRITICAL \
  --compact \
  --quiet

# Ask Claude to fix Checkov findings
claude "Checkov found security issues in our Terraform.

Checkov output:
$(checkov -d infra/terraform/modules/payment-api/ --output cli 2>/dev/null | grep -A5 'FAILED')

For each FAILED check:
1. Understand what the check is verifying (read the check ID description)
2. Implement the fix in the Terraform code
3. Re-run checkov to verify the fix
4. Add a comment in the code explaining what the fix does

Do NOT add a skip annotation (# checkov:skip) unless the finding is a genuine false positive.
If you believe a finding is a false positive, explain why and I will decide whether to skip.

Target: 0 HIGH/CRITICAL findings"`,
          },
        ]}
      />

      <h2>Terraform Module Reuse Pattern</h2>

      <SDKExample
        title="Generating Reusable Terraform Modules"
        tabs={[
          {
            label: 'bash',
            language: 'bash',
            filename: 'generate-module.sh',
            code: `# Generate a reusable Terraform module
claude "Generate a reusable Terraform module for AWS ECS Fargate services.

This module should be reusable across all our microservices (payment-api,
user-service, notification-service, etc.).

Module inputs (variables):
- service_name: string
- environment: string (dev/staging/production)
- image_uri: string (ECR image URI with tag)
- cpu/memory: number (with sensible defaults: 256/512)
- port: number (container port)
- desired_count: number (default 2)
- min_capacity / max_capacity: number (for auto-scaling)
- secrets: map(string) — map of env var name to Secrets Manager ARN
- vpc_id, private_subnet_ids: from data sources
- alb_target_group_arn: string

Module outputs:
- service_arn
- task_definition_arn  
- ecs_task_role_arn (for granting additional permissions)
- cloudwatch_log_group_name

Constraints:
- All Checkov HIGH/CRITICAL checks must pass
- Must use aws_iam_role_policy with explicit statements (no wildcard *)
- Must include auto-scaling policy (CPU-based)
- Must include tags variable merged with required tags

Place in: infra/terraform/modules/ecs-fargate-service/
Include: main.tf, variables.tf, outputs.tf, README.md"`,
          },
        ]}
      />

      <WarningBlock title="Terraform Plan Before Apply — Always">
        Never allow <code>terraform apply</code> to run without a preceding
        <code>terraform plan</code> review. In CI/CD, the plan output should be posted
        as a PR comment (using tools like Atlantis or terraform-pr-commenter), reviewed
        by a human before apply runs. Destroying and recreating a production database
        because a Terraform resource was recreated instead of updated is a career-limiting
        event. Claude can help you understand plan output: "Read the terraform plan output
        at /tmp/plan.txt and explain: what will be destroyed, what will be created,
        what will be updated in-place? Flag any destructive operations."
      </WarningBlock>

      <BestPracticeBlock title="State Backend and Locking">
        Always use a remote state backend with locking (AWS S3 + DynamoDB, Terraform Cloud,
        or similar). Local state is the fastest path to state file conflicts, accidental
        deletions, and lost state. Ask Claude to generate the backend configuration when
        creating new Terraform workspaces: "Generate the Terraform backend configuration
        for S3 state storage with DynamoDB locking. Include the S3 bucket (with versioning
        and encryption), DynamoDB table, and IAM policies for CI/CD access."
      </BestPracticeBlock>

      <NoteBlock type="tip" title="Pulumi for TypeScript-Native IaC">
        If your team is more comfortable with TypeScript than HCL, Pulumi provides
        Infrastructure as Code using real programming languages. Ask Claude to generate
        Pulumi programs rather than Terraform when your team prefers TypeScript:
        "Generate a Pulumi TypeScript program that creates the same infrastructure as
        our Terraform module in infra/terraform/modules/ecs-fargate-service/. Use the
        @pulumi/aws SDK. Apply the same security requirements from CLAUDE.md."
        Pulumi programs can be tested with standard TypeScript testing tools and have
        native support for loops, conditions, and abstractions.
      </NoteBlock>
    </article>
  )
}
