import ConceptBlock from '../../../components/content/ConceptBlock.jsx'
import SDKExample from '../../../components/content/SDKExample.jsx'
import NoteBlock from '../../../components/content/NoteBlock.jsx'
import BestPracticeBlock from '../../../components/content/BestPracticeBlock.jsx'
import WarningBlock from '../../../components/content/WarningBlock.jsx'
import SecurityCallout from '../../../components/content/SecurityCallout.jsx'

export default function AiRegulations() {
  return (
    <article className="prose-content">
      <h2>Emerging AI Regulations and Compliance Roadmap</h2>
      <p>
        The regulatory landscape for AI is evolving rapidly. The EU AI Act became law in August
        2024 and is the world's first comprehensive binding AI regulation. The US NIST AI Risk
        Management Framework (AI RMF) provides a voluntary but widely adopted governance
        structure. Executive orders, sector-specific guidance (FDA, FFIEC, HIPAA for health AI),
        and forthcoming national AI laws add further complexity. Building an AI compliance
        programme now — before enforcement deadlines — is far cheaper than retrofitting controls
        under time pressure.
      </p>

      <h2>EU AI Act</h2>

      <ConceptBlock term="EU AI Act Risk Tiers">
        <p>
          The EU AI Act classifies AI systems by risk level. <strong>Unacceptable risk</strong>
          systems (e.g., social scoring, real-time biometric surveillance) are banned.
          <strong>High-risk</strong> systems (AI used in employment, credit, education,
          critical infrastructure, law enforcement) must meet requirements for risk management,
          data governance, transparency, human oversight, accuracy, and robustness before
          deployment. <strong>Limited-risk</strong> systems (chatbots, deepfakes) require
          transparency disclosures. <strong>Minimal-risk</strong> systems have no mandatory
          obligations. Most enterprise AI agents fall into the limited-risk or, depending on
          use case, high-risk tier.
        </p>
      </ConceptBlock>

      <SecurityCallout severity="high" title="High-Risk AI Systems Face Significant EU AI Act Obligations">
        If your AI agent is used in HR (screening resumes, evaluating employees), credit scoring,
        insurance underwriting, or access to essential services, it is likely classified as
        high-risk under Annex III of the EU AI Act. High-risk systems must register in the EU
        AI database, undergo conformity assessment, maintain technical documentation, implement
        human oversight measures, and meet accuracy and robustness standards before deployment.
        Fines for non-compliance reach €30M or 6% of global annual turnover.
      </SecurityCallout>

      <SDKExample
        title="EU AI Act Transparency Disclosure for a Chatbot Agent"
        tabs={{
          python: `import anthropic

client = anthropic.Anthropic()

# EU AI Act Article 52: Users must be informed when interacting with an AI system.
# This disclosure is required for chatbots and must be "clear and distinguishable."

EU_AI_ACT_DISCLOSURE = (
    "You are interacting with an AI assistant powered by Claude. "
    "This is an automated AI system, not a human. "
    "Responses are generated by artificial intelligence and may not always be accurate. "
    "For important decisions, please consult a qualified professional."
)

def run_agent_with_disclosure(user_message: str, session_start: bool = False) -> dict:
    """
    Run agent with mandatory EU AI Act transparency disclosure.
    Disclosure is included at session start and available on request.
    """
    messages = [{"role": "user", "content": user_message}]

    response = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=1024,
        system=(
            "You are a helpful assistant. "
            "If asked whether you are an AI or human, always confirm you are an AI. "
            "You must never claim to be human."
        ),
        messages=messages,
    )

    answer = response.content[0].text

    return {
        "response": answer,
        "ai_disclosure": EU_AI_ACT_DISCLOSURE if session_start else None,
        "is_ai": True,
        "model": "claude-opus-4-5",
    }

# High-risk AI: additional logging for conformity assessment evidence
def log_high_risk_decision(
    agent_id: str,
    user_id: str,
    decision_type: str,  # e.g. "credit_assessment", "resume_screening"
    input_summary: str,
    output_summary: str,
    human_reviewed: bool,
    reviewer_id: str | None = None,
) -> dict:
    """
    Log high-risk AI decisions for EU AI Act Art. 12 (logging requirements).
    High-risk systems must log enough to enable post-hoc monitoring.
    """
    import time, uuid
    record = {
        "log_id": str(uuid.uuid4()),
        "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "agent_id": agent_id,
        "user_id": user_id,
        "decision_type": decision_type,
        "input_hash": __import__("hashlib").sha256(input_summary.encode()).hexdigest(),
        "output_summary": output_summary[:500],  # Truncated for log
        "human_reviewed": human_reviewed,
        "reviewer_id": reviewer_id,
        "eu_ai_act_risk_tier": "high",
        "article_12_compliant": True,
    }
    import logging
    logging.getLogger("eu_ai_act").info(__import__("json").dumps(record))
    return record`,
          typescript: `import Anthropic from '@anthropic-ai/sdk'
import { randomUUID } from 'crypto'
import * as crypto from 'crypto'

const client = new Anthropic()

const EU_AI_ACT_DISCLOSURE =
  'You are interacting with an AI assistant. This is an automated AI system, not a human. ' +
  'Responses are generated by artificial intelligence and may not always be accurate.'

async function runAgentWithDisclosure(userMessage: string, sessionStart = false) {
  const response = await client.messages.create({
    model: 'claude-opus-4-5',
    max_tokens: 1024,
    system: 'You are a helpful assistant. Always confirm you are an AI if asked.',
    messages: [{ role: 'user', content: userMessage }],
  })

  return {
    response: (response.content[0] as Anthropic.TextBlock).text,
    aiDisclosure: sessionStart ? EU_AI_ACT_DISCLOSURE : null,
    isAi: true,
  }
}

function logHighRiskDecision(params: {
  agentId: string
  userId: string
  decisionType: string
  inputSummary: string
  outputSummary: string
  humanReviewed: boolean
  reviewerId?: string
}) {
  const record = {
    logId: randomUUID(),
    timestampUtc: new Date().toISOString(),
    ...params,
    inputHash: crypto.createHash('sha256').update(params.inputSummary).digest('hex'),
    outputSummary: params.outputSummary.slice(0, 500),
    euAiActRiskTier: 'high',
    article12Compliant: true,
  }
  console.info(JSON.stringify(record))
  return record
}`,
        }}
      />

      <h2>NIST AI Risk Management Framework</h2>

      <ConceptBlock term="NIST AI RMF Core Functions">
        <p>
          The NIST AI RMF organises AI risk management into four core functions: <strong>GOVERN</strong>
          (policies, roles, culture), <strong>MAP</strong> (identify and categorise risks),
          <strong>MEASURE</strong> (evaluate and test risk), and <strong>MANAGE</strong>
          (treat and respond to risk). Unlike the EU AI Act, the AI RMF is voluntary but serves
          as the primary US government guidance and is widely used by US federal contractors.
          Many enterprise AI governance programmes use it as a complement to ISO 27001 and SOC 2.
        </p>
      </ConceptBlock>

      <SDKExample
        title="NIST AI RMF Risk Register Entry Template"
        tabs={{
          python: `# NIST AI RMF MAP 2.2 — Risk Register for an AI agent system
# This is a data structure for documentation, not executable logic.

AI_RISK_REGISTER = {
    "system": "Customer Support AI Agent",
    "version": "2.1.0",
    "last_updated": "2025-03-01",
    "nist_ai_rmf_version": "1.0",
    "risks": [
        {
            "risk_id": "AI-001",
            "category": "Trustworthiness — Fairness",
            "description": "Agent may produce responses that are biased against protected groups",
            "nist_category": "MAP 2.3",
            "likelihood": "medium",
            "impact": "high",
            "inherent_risk_score": 12,
            "controls": [
                "Regular bias evaluation on diverse test sets",
                "Diverse review panel for system prompt changes",
                "Output monitoring for demographic disparities",
            ],
            "residual_risk_score": 4,
            "owner": "ml-platform-team@company.com",
            "review_date": "2025-06-01",
        },
        {
            "risk_id": "AI-002",
            "category": "Trustworthiness — Explainability",
            "description": "Agent cannot explain reasoning for high-stakes decisions",
            "nist_category": "MAP 2.2",
            "likelihood": "high",
            "impact": "medium",
            "inherent_risk_score": 12,
            "controls": [
                "Chain-of-thought prompting to surface reasoning",
                "Human review required for high-stakes outputs",
                "Confidence score thresholds before automated action",
            ],
            "residual_risk_score": 6,
            "owner": "ai-governance@company.com",
            "review_date": "2025-06-01",
        },
    ],
}`,
        }}
      />

      <WarningBlock title="Regulatory Requirements Are Use-Case Specific — Get Legal Advice">
        <p>
          Whether your AI agent is subject to the EU AI Act's high-risk requirements depends on
          its specific use case, the sector it operates in, and who the affected individuals are.
          This content provides educational context, not legal advice. Engage a qualified legal
          counsel with AI regulatory expertise to assess your specific obligations before deploying
          agents in regulated use cases.
        </p>
      </WarningBlock>

      <BestPracticeBlock title="Build a Compliance Roadmap Keyed to Regulatory Deadlines">
        <p>
          The EU AI Act has staggered implementation deadlines: prohibited AI systems must be
          withdrawn by February 2025, GPAI model obligations apply from August 2025, and
          high-risk system requirements apply from August 2026. Map each deadline to the gap
          between your current controls and the requirement, then build a prioritised roadmap.
          Starting with the NIST AI RMF GOVERN function (policies and roles) is low-cost, high-value,
          and creates the foundation for all subsequent technical controls.
        </p>
      </BestPracticeBlock>

      <NoteBlock type="info" title="GPAI Model vs. AI System Obligations">
        <p>
          The EU AI Act distinguishes between General-Purpose AI (GPAI) models (like Claude,
          GPT-4, Gemini) and AI systems built on top of them (your agent application). GPAI
          model providers must publish technical documentation and comply with copyright rules.
          Deployers of AI systems built on GPAI models have separate obligations tied to the
          risk tier of their specific use case. Using Anthropic's Claude API means Anthropic
          is the GPAI model provider; your application is the AI system deployer.
        </p>
      </NoteBlock>
    </article>
  )
}
