import ConceptBlock from '../../../components/content/ConceptBlock.jsx';
import NoteBlock from '../../../components/content/NoteBlock.jsx';
import SDKExample from '../../../components/content/SDKExample.jsx';
import BestPracticeBlock from '../../../components/content/BestPracticeBlock.jsx';

export default function HyDE() {
  return (
    <div className="lesson-content">
      <h2>HyDE — Hypothetical Document Embeddings</h2>

      <p>
        Standard RAG embeds the user's question and searches for documents that are semantically
        close to it. This works well when questions and documents are phrased similarly, but
        breaks down when a short, ambiguous question is far in embedding space from the verbose,
        technical document that actually answers it. HyDE bridges this gap by generating a
        hypothetical answer first and using that as the search query.
      </p>

      <ConceptBlock
        title="HyDE (Hypothetical Document Embeddings)"
        definition="HyDE is a retrieval technique that asks a language model to generate a hypothetical answer to the user's question — without access to any documents — and then embeds that hypothetical answer rather than the original question. The intuition is that a plausible answer, even if factually incorrect, will be phrased in the same style and vocabulary as the real answer documents, making it a better semantic match."
      />

      <h2>Why HyDE Improves Retrieval</h2>

      <p>
        Consider the query: "What causes the aurora borealis?" This 5-word question sits in a
        different region of embedding space from a 300-word Wikipedia paragraph about solar wind
        and magnetospheric physics. A hypothetical answer generated by an LLM — "The aurora borealis
        is caused by charged particles from the sun interacting with Earth's magnetic field..." —
        uses the same terminology and sentence structure as the real document, closing the
        embedding space gap.
      </p>

      <p>
        HyDE is especially effective for: domain-specific technical corpora where question phrasing
        differs sharply from document phrasing, scientific literature retrieval, legal document
        search, and low-resource domains where sparse training data means embedding models have weak
        coverage of the domain vocabulary.
      </p>

      <h2>When HyDE Hurts</h2>

      <p>
        HyDE assumes the LLM can generate a plausible hypothetical answer even without grounding.
        If the LLM has no knowledge of the domain, its hypothetical answer will be generic or
        wrong — and may retrieve less relevant documents than a direct question embedding. Test
        HyDE empirically against your corpus before adopting it; it is not universally beneficial.
      </p>

      <SDKExample
        title="HyDE Implementation"
        tabs={{
          python: `import anthropic
import voyageai
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams

anthropic_client = anthropic.Anthropic()
voyage_client = voyageai.Client()
qdrant = QdrantClient(":memory:")  # Use real URL in production

HYDE_SYSTEM = """Generate a hypothetical document passage that would answer the following question.
Write 2-3 sentences as if you are the document, not the answer. Use domain-appropriate vocabulary.
Do NOT say you are generating a hypothetical answer — just write the passage directly."""

def generate_hypothetical_document(question: str) -> str:
    """Use LLM to generate a hypothetical answer passage."""
    response = anthropic_client.messages.create(
        model="claude-haiku-4-5",   # Use fast/cheap model for HyDE generation
        max_tokens=256,
        temperature=0.3,
        system=HYDE_SYSTEM,
        messages=[{"role": "user", "content": question}]
    )
    return response.content[0].text

def hyde_retrieve(question: str, collection: str, top_k: int = 5) -> list[dict]:
    """Retrieve using HyDE: embed hypothetical answer instead of question."""
    # Generate hypothetical document
    hypothetical = generate_hypothetical_document(question)
    print(f"Hypothetical: {hypothetical[:120]}...")

    # Embed the hypothetical document (not the question)
    result = voyage_client.embed([hypothetical], model="voyage-3")
    hyde_vector = result.embeddings[0]

    # Search with hypothetical embedding
    hits = qdrant.search(
        collection_name=collection,
        query_vector=hyde_vector,
        limit=top_k,
    )
    return [{"content": h.payload["content"], "score": h.score} for h in hits]

def standard_retrieve(question: str, collection: str, top_k: int = 5) -> list[dict]:
    """Standard retrieval: embed question directly."""
    result = voyage_client.embed([question], model="voyage-3")
    query_vector = result.embeddings[0]
    hits = qdrant.search(
        collection_name=collection,
        query_vector=query_vector,
        limit=top_k,
    )
    return [{"content": h.payload["content"], "score": h.score} for h in hits]

# Usage comparison
question = "What are the side effects of combining ACE inhibitors with potassium supplements?"
hyde_results = hyde_retrieve(question, "medical-docs")
standard_results = standard_retrieve(question, "medical-docs")`,
        }}
      />

      <h2>HyDE with Multiple Hypothetical Documents</h2>

      <p>
        A single hypothetical document may not capture all relevant angles of a complex question.
        Generate 3–5 hypothetical documents with slight temperature variation, embed all of them,
        and either average the vectors or retrieve independently and merge the result sets.
        Averaging the embeddings (sometimes called "centroid HyDE") produces a more stable
        search vector that is less sensitive to the specific phrasing of any single generation.
      </p>

      <SDKExample
        title="Multi-Hypothetical HyDE with Vector Averaging"
        tabs={{
          python: `import numpy as np
import anthropic
import voyageai

anthropic_client = anthropic.Anthropic()
voyage_client = voyageai.Client()

def multi_hyde_retrieve(question: str, num_hypotheticals: int = 3) -> np.ndarray:
    """Generate multiple hypotheticals and average their embeddings."""
    hypotheticals = []
    for i in range(num_hypotheticals):
        response = anthropic_client.messages.create(
            model="claude-haiku-4-5",
            max_tokens=200,
            temperature=0.5,   # Higher temp for diverse hypotheticals
            system="Write a passage from a document that would answer this question.",
            messages=[{"role": "user", "content": question}]
        )
        hypotheticals.append(response.content[0].text)

    # Embed all hypotheticals in a single batch call
    result = voyage_client.embed(hypotheticals, model="voyage-3")
    vectors = np.array(result.embeddings)

    # Average the vectors to get a centroid
    centroid = vectors.mean(axis=0)

    # Normalize to unit length (important for cosine similarity)
    centroid = centroid / np.linalg.norm(centroid)
    return centroid

# The centroid is more robust than any single hypothetical vector
centroid_vector = multi_hyde_retrieve(
    "How does transformer attention scale with sequence length?"
)
print(f"Centroid vector shape: {centroid_vector.shape}")`,
        }}
      />

      <BestPracticeBlock title="Use a Fast, Cheap Model for HyDE Generation">
        <p>
          HyDE adds an extra LLM call to every query. Use your fastest, cheapest model for this
          step — a small model like claude-haiku or GPT-4o-mini generates hypothetical documents
          of sufficient quality for most domains. Reserve your stronger model for the final answer
          generation step. This keeps the latency and cost overhead of HyDE manageable.
        </p>
      </BestPracticeBlock>

      <NoteBlock
        title="Always A/B test HyDE against direct retrieval"
        content="HyDE is not universally better. Measure retrieval recall@5 with both approaches on your golden dataset. Common finding: HyDE helps on technical or scientific corpora where question phrasing diverges from document phrasing. It often does not help — and can hurt — on conversational or short-document corpora where questions and documents use similar vocabulary. Treat it as one tool to evaluate, not a default upgrade."
      />
    </div>
  );
}
